[package]
name = "cad"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = { version = "0.34.0", features = ["serde-serialize"] }
rand = "0.9.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tracing = "0.1.41"
tracing-log = "0.2.0"
